fix: Do not use `EventDispatcherInterface` but OCP `IEventDispatcher`
The interfaces were changed on current master (upcoming Nextcloud 28),
so the event dispatcher for the User class should be the interface from OCP
instead of directly use the Symfony dispatcher.

Fixes:
> TypeError: OC\User\User::__construct(): Argument #3 ($dispatcher) must be of type OCP\EventDispatcher\IEventDispatcher, OC\EventDispatcher\SymfonyAdapter given, called in /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php on line 69 and defined in /var/www/html/lib/private/User/User.php:105

Signed-off-by: Ferdinand Thiessen <opensource@fthiessen.de>